### ISSUE TITLE
Allow view_private optionally for Strava authorization

### ISSUE THREAD

**Issue by hozn** [hozn/freezingsaddles#11]
Strava changed their API so that view_private is a separate permission.  We should allow users the option of authorizing the app to view their private rides.

**Comment by jrenaut** [comment]
I think this might be more headache than it's worth - we'd have to explain what the permission does, and people would have questions. Seems like it would cause more support issues than it would solve. But maybe you're already getting a ton of support requests already, I don't know

**Comment by hozn** [comment]
Yeah, it might.  Probably will try it to see if there is complaint; for folks already registered (most) this probably won't be a concern unless they choose to re-authorize.  I was thinking just radio buttons, like:

[x] Only allow Freezing Saddles to count miles from public rides.
[ ] Allow Freezing Saddles to also count miles from my rides marked "private".

**Comment by jrenaut** [comment]
Right. Not something I think you or I would have a problem with, but I'm constantly surprised by how private people are about their Strava rides, and how little people read of sign-up forms.

**Comment by hozn** [comment]
Well, we shall see.  If it results in support requests, we can remove the
option.
