### ISSUE TITLE
Optimize and smooth strava requests to avoid exceeding rate limits.

### ISSUE THREAD

**Issue by hozn** [hozn/freezingsaddles#15]
- Review the need for a --rewrite option on ride sync.  (Check key attribs and queue for full-rewrite only if needed?)
- Consolidate the logic that operates on a full activity ("detail" level) fetch.
- Remove unnecessary fetching of photos (only fetch photos if ride has photos also try to get the easy wins in the activity detail sync stage).
- Use modulus to spread out detail ride processing.  Add bookkeeping for ride tracking (detail_fetched col?).  E.g. if we run a script hourly, use activity_id % 24 == 0 to figure out if we should resync it.
- Finally, add bookkeeping to athlete table to track last sync and rewrite times.  Display this in the UI, as it might preempt some support questions.

**Comment by jrenaut** [comment]
When you're messing with the import, can you also get the [related activities](https://strava.github.io/api/v3/activities/#get-related)? A dump into a table with activity_id and related_activity_id is all I think I'd need.

**Comment by hozn** [comment]
Ok, I added #18 to track that request.

**Comment by hozn** [comment]
I think we're good on the requests now . Aggressive caching of strava content and "--only-cache" script options make it less expensive to add new data points to track now.
