### ISSUE TITLE
Highcharts CDN is http so some browsers are blocking

### ISSUE THREAD

**Issue by jrenaut** [hozn/freezingsaddles#23]
The Highcharts CDN is http-only so now that we're using https, some browsers (Chrome for sure, probably others) are blocking the js files, meaning charts don't work.

Is this just a matter of adding the js file to the static/js directory and updating links in templates, or is there additional static file handling that needs to happen?

**Comment by hozn** [comment]
Interesting, this claims that https is supported: http://www.highcharts.com/download

(I didn't even know/remember we were using Highcharts yet.)

Alternatively, yes, we can definitely just add the files locally.

**Comment by jrenaut** [comment]
I looked at their CDN and all the listed urls are http. I'll check again, otherwise I'll just download to static/js

**Comment by hozn** [comment]
Yeah, not sure, they had this example:
```
<script src="https://code.highcharts.com"></script>
```
Which does seem to load fine.
